import { useState, useMemo } from "react";
import DashboardLayout from "./components/layout/DashboardLayout";
import DateAnalysisFilters from "./components/layout/DateAnalysisFilters";
import AustraliaMap from "./components/map/AustraliaMap";
import SuitabilityCalendar from "./components/calendar/SuitabilityCalendar";
import TemperatureChart from "./components/charts/TemperatureChart";
import HumidityChart from "./components/charts/HumidityChart";
import WindSpeedChart from "./components/charts/WindSpeedChart";
import UVIndexChart from "./components/charts/UVIndexChart";
import RecommendationPanel from "./components/recommendation/RecommendationPanel";
import LocationComparison from "./components/comparison/LocationComparison";
import Card from "./components/common/Card";
import SummaryMetric from "./components/common/SummaryMetric";
import RiskIndicator from "./components/common/RiskIndicator";
import { locations, getDataForGranularity, suitabilityConfig } from "./data/placeholderData";
import { MapPin, CalendarDays, BarChart3, ShieldCheck, GitCompareArrows, Rocket, Thermometer, Droplets, Wind, Sun, Gauge, Download, RotateCcw } from "lucide-react";

export default function App() {
  const [locationId, setLocationId] = useState("melbourne");
  const [granularity, setGranularity] = useState("daily");
  const [selectedMonth, setSelectedMonth] = useState(9);
  const [selectedYear, setSelectedYear] = useState(2025);
  const [eventType, setEventType] = useState("Marathon");
  const [selectedDay, setSelectedDay] = useState(5);
  const [selectedSuburb, setSelectedSuburb] = useState("Melbourne CBD");
  const [planGenerated, setPlanGenerated] = useState(false);

  const location = locations.find((l) => l.id === locationId) || locations[0];

  const chartData = useMemo(
    () => getDataForGranularity(location, granularity, selectedYear, selectedMonth),
    [location, granularity, selectedYear, selectedMonth]
  );

  const xKey = granularity === "daily" ? "day"
    : granularity === "monthly" ? "label"
    : granularity === "quarterly" ? "key"
    : "year";

  const dayData = granularity === "daily"
    ? chartData.find((d) => d.day === selectedDay) || chartData[0]
    : chartData[0];

  const handleLocationChange = (id) => {
    setLocationId(id);
    const loc = locations.find((l) => l.id === id);
    if (loc?.suburbs?.length) setSelectedSuburb(loc.suburbs[0]);
  };

  const handleReset = () => {
    setLocationId("melbourne");
    setGranularity("daily");
    setSelectedMonth(9);
    setSelectedYear(2025);
    setEventType("Marathon");
    setSelectedDay(5);
    setSelectedSuburb("Melbourne CBD");
    setPlanGenerated(false);
  };

  const handleGeneratePlan = () => {
    setPlanGenerated(true);
    setTimeout(() => {
      document.getElementById("start-planning-result")?.scrollIntoView({ behavior: "smooth" });
    }, 100);
  };

  const cfg = dayData ? (suitabilityConfig[dayData.suitability] || suitabilityConfig.slightly_suitable) : suitabilityConfig.slightly_suitable;

  const exportSummary = () => {
    if (!dayData) return;
    const lines = [
      "Marathon Weather Planning - Summary Report",
      "==========================================",
      `Location: ${selectedSuburb} (${location.name}, ${location.state})`,
      `Suitability: ${cfg.label}`,
      `Score: ${dayData.score}/100`,
      `Temperature: ${dayData.temp}\u00b0C`,
      `Humidity: ${dayData.humidity}%`,
      `Wind: ${dayData.wind} km/h`,
      `UV Index: ${dayData.uv}`,
      `Confidence: ${location.confidence}`,
      "",
      "Generated by Marathon Weather Planning Dashboard",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url;
    a.download = `marathon-summary-${location.id}.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  const filterProps = {
    locationId, onLocationChange: handleLocationChange,
    granularity, onGranularityChange: setGranularity,
    selectedMonth, onMonthChange: setSelectedMonth,
    selectedYear, onYearChange: setSelectedYear,
    eventType, onEventTypeChange: setEventType,
  };

  return (
    <DashboardLayout planGenerated={planGenerated}>
      {/* ====== 2. MAP EXPLORER ====== */}
      <section id="map-explorer" aria-label="Map explorer">
        <Card title="Map Explorer" subtitle="Explore and select your marathon location" icon={MapPin}>
          <AustraliaMap
            locationId={locationId}
            onSelectLocation={handleLocationChange}
            selectedSuburb={selectedSuburb}
            onSelectSuburb={setSelectedSuburb}
            selectedMonth={selectedMonth}
            selectedYear={selectedYear}
          />
        </Card>
      </section>

      {/* ====== 3. DATE ANALYSIS ====== */}
      <section id="date-analysis" className="space-y-6" aria-label="Date analysis">
        <DateAnalysisFilters {...filterProps} />

        <Card title="Weather Conditions" subtitle="Raw weather data for the selected location and time period" icon={BarChart3}>
          {dayData && (
            <div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              <div className="flex items-center gap-3 rounded-lg border border-[var(--border)] bg-[var(--bg)] p-4">
                <Thermometer className="h-5 w-5 text-red-500" aria-hidden="true" />
                <div>
                  <p className="text-xs text-[var(--text-muted)]">Temperature</p>
                  <p className="text-lg font-bold text-[var(--text)]">{dayData.temp}&deg;C</p>
                </div>
              </div>
              <div className="flex items-center gap-3 rounded-lg border border-[var(--border)] bg-[var(--bg)] p-4">
                <Droplets className="h-5 w-5 text-blue-500" aria-hidden="true" />
                <div>
                  <p className="text-xs text-[var(--text-muted)]">Humidity</p>
                  <p className="text-lg font-bold text-[var(--text)]">{dayData.humidity}%</p>
                </div>
              </div>
              <div className="flex items-center gap-3 rounded-lg border border-[var(--border)] bg-[var(--bg)] p-4">
                <Wind className="h-5 w-5 text-teal-500" aria-hidden="true" />
                <div>
                  <p className="text-xs text-[var(--text-muted)]">Wind Speed</p>
                  <p className="text-lg font-bold text-[var(--text)]">{dayData.wind} km/h</p>
                </div>
              </div>
              <div className="flex items-center gap-3 rounded-lg border border-[var(--border)] bg-[var(--bg)] p-4">
                <Sun className="h-5 w-5 text-orange-500" aria-hidden="true" />
                <div>
                  <p className="text-xs text-[var(--text-muted)]">UV Index</p>
                  <p className="text-lg font-bold text-[var(--text)]">{dayData.uv}</p>
                </div>
              </div>
            </div>
          )}
          <div className="grid gap-4 md:grid-cols-2">
            <TemperatureChart data={chartData} xKey={xKey} />
            <HumidityChart data={chartData} xKey={xKey} />
            <WindSpeedChart data={chartData} xKey={xKey} />
            <UVIndexChart data={chartData} xKey={xKey} />
          </div>
        </Card>
      </section>

      {/* ====== 4. START PLANNING ====== */}
      <section id="start-planning" className="space-y-6" aria-label="Start planning">
        {!planGenerated ? (
          <div className="rounded-xl border border-[var(--border)] bg-white p-10 text-center shadow-sm">
            <Rocket className="mx-auto h-10 w-10 text-[var(--accent)]" aria-hidden="true" />
            <h2 className="mt-4 text-2xl font-bold text-[var(--primary)]">Generate Your Event Plan</h2>
            <p className="mx-auto mt-3 max-w-lg text-sm leading-relaxed text-[var(--text-secondary)]">
              You have selected <strong className="text-[var(--text)]">{selectedSuburb}</strong> in{" "}
              <strong className="text-[var(--text)]">{location.name}, {location.state}</strong>.
              Click below to calculate the suitability score and generate your event summary.
            </p>
            <button
              type="button"
              onClick={handleGeneratePlan}
              className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[var(--accent)] px-8 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-[var(--accent-light)]"
            >
              Generate Plan
            </button>
          </div>
        ) : (
          <div id="start-planning-result" className="space-y-6">
            {/* Score result */}
            <div className="grid gap-6 lg:grid-cols-[1fr_1fr]">
              <Card title="Suitability Result" subtitle="Final score based on weather conditions" icon={ShieldCheck}>
                <div className="space-y-4">
                  <div className="flex items-center gap-4">
                    <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-[var(--bg)]">
                      <span className="text-3xl font-bold text-[var(--primary)]">{dayData?.score || 0}</span>
                    </div>
                    <div>
                      <p className="text-sm text-[var(--text-muted)]">out of 100</p>
                      {dayData && <RiskIndicator suitability={dayData.suitability} />}
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <SummaryMetric icon={Thermometer} label="Temperature" value={`${dayData?.temp || 0}\u00b0C`} />
                    <SummaryMetric icon={Droplets} label="Humidity" value={`${dayData?.humidity || 0}%`} />
                    <SummaryMetric icon={Wind} label="Wind" value={`${dayData?.wind || 0} km/h`} />
                    <SummaryMetric icon={Sun} label="UV Index" value={`${dayData?.uv || 0}`} />
                  </div>
                  <div className="flex items-center gap-2">
                    <ShieldCheck className="h-4 w-4 text-[var(--text-muted)]" />
                    <span className="text-xs text-[var(--text-secondary)]">{location.confidence} forecast confidence</span>
                  </div>
                </div>
              </Card>

              <Card title="Event Summary" subtitle="Your selected marathon parameters" icon={MapPin}>
                <div className="space-y-4">
                  <div className="rounded-lg border border-[var(--border)] bg-[var(--bg)] p-4">
                    <p className="text-xs text-[var(--text-muted)]">Location</p>
                    <p className="mt-0.5 text-base font-semibold text-[var(--text)]">{selectedSuburb}</p>
                    <p className="text-sm text-[var(--text-secondary)]">{location.name}, {location.state}</p>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="rounded-lg border border-[var(--border)] bg-[var(--bg)] p-3">
                      <p className="text-[10px] text-[var(--text-muted)]">Event Type</p>
                      <p className="mt-0.5 text-sm font-semibold text-[var(--text)]">{eventType}</p>
                    </div>
                    <div className="rounded-lg border border-[var(--border)] bg-[var(--bg)] p-3">
                      <p className="text-[10px] text-[var(--text-muted)]">Time Scale</p>
                      <p className="mt-0.5 text-sm font-semibold text-[var(--text)]">{granularity.charAt(0).toUpperCase() + granularity.slice(1)}</p>
                    </div>
                  </div>

                  {/* Score explanation */}
                  <div className="rounded-lg border-l-4 border-l-[var(--accent-blue)] bg-blue-50 px-4 py-3">
                    <p className="text-xs font-semibold text-[var(--primary)]">How the score is calculated</p>
                    <p className="mt-1 text-[11px] leading-relaxed text-[var(--text-secondary)]">
                      The score combines temperature (penalised above 25&deg;C), humidity (above 60%), 
                      wind speed (above 15 km/h), and UV index (above 6) into a 0&ndash;100 composite.{" "}
                      <strong className="text-green-700">70+</strong> = Suitable,{" "}
                      <strong className="text-amber-700">45&ndash;69</strong> = Slightly Suitable,{" "}
                      <strong className="text-red-700">&lt;45</strong> = Not Suitable.
                    </p>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <button type="button" onClick={handleReset}
                      className="inline-flex items-center justify-center gap-2 rounded-lg border border-[var(--border)] bg-white px-4 py-2.5 text-sm font-semibold text-[var(--text-secondary)] transition hover:bg-[var(--bg)]">
                      <RotateCcw className="h-3.5 w-3.5" /> Reset
                    </button>
                    <button type="button" onClick={exportSummary}
                      className="inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-[var(--accent-light)]">
                      <Download className="h-3.5 w-3.5" /> Export
                    </button>
                  </div>
                </div>
              </Card>
            </div>
          </div>
        )}
      </section>

      {/* ====== 5. COMPARISON (locked until plan generated) ====== */}
      <section id="comparison" aria-label="Comparison">
        {planGenerated ? (
          <Card title="Location Comparison" subtitle="Compare weather attributes across locations" icon={GitCompareArrows}>
            <LocationComparison
              granularity={granularity}
              selectedYear={selectedYear}
              selectedMonth={selectedMonth}
            />
          </Card>
        ) : (
          <div className="rounded-xl border border-dashed border-[var(--border)] bg-[var(--surface-alt)] p-10 text-center">
            <GitCompareArrows className="mx-auto h-8 w-8 text-[var(--text-muted)]" aria-hidden="true" />
            <h3 className="mt-3 text-sm font-semibold text-[var(--text-secondary)]">Comparison Available After Planning</h3>
            <p className="mx-auto mt-2 max-w-sm text-xs leading-relaxed text-[var(--text-muted)]">
              Generate your event plan first, then come back here to compare locations and scenarios side by side.
            </p>
          </div>
        )}
      </section>
    </DashboardLayout>
  );
}
