import { MapPin, Calendar, Clock3, Gauge, ShieldCheck, RotateCcw, Download } from "lucide-react";
import SummaryMetric from "../common/SummaryMetric";
import RiskIndicator from "../common/RiskIndicator";
import { suitabilityConfig } from "../../data/placeholderData";

export default function RecommendationPanel({ location, selectedSuburb, dayData, granularity, onReset }) {
  if (!dayData) return null;

  const cfg = suitabilityConfig[dayData.suitability] || suitabilityConfig.slightly_suitable;

  const exportSummary = () => {
    const lines = [
      `Marathon Weather Planning - Summary Report`,
      `==========================================`,
      `Location: ${selectedSuburb} (${location.name}, ${location.state})`,
      `Suitability: ${cfg.label}`,
      `Score: ${dayData.score}/100`,
      `Temperature: ${dayData.temp}\u00b0C`,
      `Humidity: ${dayData.humidity}%`,
      `Wind: ${dayData.wind} km/h`,
      `UV Index: ${dayData.uv}`,
      `Confidence: ${location.confidence}`,
      ``,
      `Generated by Marathon Weather Planning Dashboard`,
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `marathon-summary-${location.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Location summary */}
      <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Selected Location</p>
        <p className="mt-1 text-base font-semibold text-slate-900">{selectedSuburb}</p>
        <p className="mt-1.5 text-sm text-slate-500">{location.name}, {location.state}</p>
      </div>

      {/* Quick metrics */}
      <div className="grid grid-cols-2 gap-3">
        <SummaryMetric icon={Gauge} label="Score" value={`${dayData.score}/100`} />
        <SummaryMetric icon={Clock3} label="Temp" value={`${dayData.temp}\u00b0C`} />
      </div>

      {/* Suitability + confidence */}
      <div className="flex flex-wrap items-center gap-2">
        <RiskIndicator suitability={dayData.suitability} />
        <span className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-medium text-slate-600">
          <ShieldCheck className="h-3 w-3" aria-hidden="true" />
          {location.confidence} confidence
        </span>
      </div>

      {/* Dark summary card */}
      <div className="rounded-xl bg-gradient-to-br from-slate-900 to-slate-800 p-4 shadow-lg">
        <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-sky-300">
          Event Summary
        </p>
        <div className="grid grid-cols-2 gap-3">
          <SummaryMetric icon={MapPin} label="Location" value={selectedSuburb} dark />
          <SummaryMetric icon={Gauge} label="Score" value={`${dayData.score}/100`} dark />
          <SummaryMetric icon={Calendar} label="Humidity" value={`${dayData.humidity}%`} dark />
          <SummaryMetric icon={ShieldCheck} label="Suitability" value={cfg.label} dark />
        </div>
      </div>

      {/* Actions */}
      <div className="grid grid-cols-2 gap-3">
        <button
          type="button"
          onClick={onReset}
          className="inline-flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500"
        >
          <RotateCcw className="h-3.5 w-3.5" aria-hidden="true" />
          Reset
        </button>
        <button
          type="button"
          onClick={exportSummary}
          className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500"
        >
          <Download className="h-3.5 w-3.5" aria-hidden="true" />
          Export
        </button>
      </div>
    </div>
  );
}
